// web/components/Anchor.vue
<template>
  <div
    ref="container"
    class="flex flex-col bg-white b-rounded-4 max-h-[700px] overflow-y-auto"
  >
    <div
      class="line-height-6 text-6 light_border_bottom p-b-5 dark_text_white p-2 pl-4 pt-5"
    >
      目录
    </div>
    <div
      v-for="(anchor, index) in anchors"
      :style="{
        padding: `10px 0 10px ${anchor.depth * anchor.depth * anchor.depth}px`,
      }"
      :key="index"
    >
      <a
        style="cursor: pointer"
        class="p-l-6"
        :class="{
          'anchor_border text-5 text-#1e80ff font-bold active':
            anchor.id == lineIdx,
        }"
        :href="'#' + anchor.id"
        @click="click(anchor)"
        >{{ anchor.text }}</a
      >
    </div>
  </div>
</template>

<script lang="ts" setup>
const props = defineProps<{
  toc: Toc[];
  lineIndex: string;
}>();

const lineIdx = ref("");

type Toc = {
  id: string;
  depth: number;
  text: string;
  children: Toc[];
};

// 将 toc 逐渐展开并合并到 anchors 中
const anchors = ref<Toc[]>([]);
watch(
  () => props.toc,
  (newValue) => {
    anchors.value = [];
    expandToc(newValue, 1);
  },
  { immediate: true },
);

function expandToc(toc: Toc[], depth: number = 1) {
  toc.forEach((item) => {
    anchors.value.push(item);
    if (item.children) {
      expandToc(item.children, depth + 1);
    }
  });
}

const container = ref();

const click = (toc: Toc) => {
  lineIdx.value = toc.id;
};

watch(
  () => props.lineIndex,
  async (newValue, oldValue) => {
    if (newValue !== oldValue) {
      await nextTick();
      lineIdx.value = newValue;
      const activeElement = container.value.querySelector(".active");
      if (activeElement) {
        const elementPosition =
          activeElement.offsetTop - container.value.offsetTop;
        // 判断元素是否超过当前 container 高度的一半
        if (elementPosition > container.value.clientHeight / 2) {
          container.value.scrollTop =
            elementPosition - container.value.clientHeight / 2;
        } else {
          container.value.scrollTop = 0;
        }
        // container.value.scrollTop = elementPosition - 20;
      }
    }
  },
);
</script>

// nextjs-web/app/components/Anchor.tsx
'use client'; // 添加客户端渲染标记

import { useRef, useState, useEffect } from 'react';

// 定义 Toc 类型
export type Toc = {
  id: string;
  depth: number;
  text: string;
  children: Toc[];
};

// 定义组件 Props
interface AnchorProps {
  toc: Toc[];
  lineIndex: string;
}

export default function Anchor({ toc, lineIndex }: AnchorProps) {
  const [anchors, setAnchors] = useState<Toc[]>([]);
  const [lineIdx, setLineIdx] = useState<string>('');
  const containerRef = useRef<HTMLDivElement>(null);

  // 将 toc 展开并合并到 anchors 中
  const expandToc = (tocItems: Toc[], depth: number = 1) => {
    const result: Toc[] = [];
    tocItems.forEach((item) => {
      result.push(item);
      if (item.children && item.children.length > 0) {
        result.push(...expandToc(item.children, depth + 1));
      }
    });
    return result;
  };

  // 监听 toc 变化，更新 anchors
  useEffect(() => {
    if (toc && toc.length > 0) {
      setAnchors(expandToc(toc, 1));
    } else {
      setAnchors([]);
    }
  }, [toc]);

  // 处理点击事件
  const handleClick = (toc: Toc) => {
    setLineIdx(toc.id);
  };

  // 监听 lineIndex 变化
  useEffect(() => {
    if (lineIndex !== lineIdx) {
      setLineIdx(lineIndex);

      // 在状态更新后处理滚动操作
      setTimeout(() => {
        const container = containerRef.current;
        if (!container) return;

        const activeElement = container.querySelector(".active");
        if (activeElement) {
          const elementPosition = activeElement.getBoundingClientRect().top - container.getBoundingClientRect().top;
          
          // 判断元素是否超过当前 container 高度的一半
          if (elementPosition > container.clientHeight / 2) {
            container.scrollTop = elementPosition - container.clientHeight / 2 + container.scrollTop;
          } else {
            container.scrollTop = 0;
          }
        }
      }, 0);
    }
  }, [lineIndex, lineIdx]);

  return (
    <div
      ref={containerRef}
      className="flex flex-col bg-white rounded-md max-h-[700px] overflow-y-auto"
    >
      <div
        className="leading-6 text-lg border-b border-gray-200 pb-1.5 dark:text-white p-2 pl-4 pt-5"
      >
        目录
      </div>
      {anchors.map((anchor, index) => (
        <div
          key={index}
          style={{
            padding: `10px 0 10px ${anchor.depth * anchor.depth * anchor.depth}px`,
          }}
        >
          <a
            style={{ cursor: 'pointer' }}
            className={`pl-6 ${
              anchor.id === lineIdx
                ? 'anchor_border text-base text-[#1e80ff] font-bold active'
                : ''
            }`}
            href={`#${anchor.id}`}
            onClick={() => handleClick(anchor)}
          >
            {anchor.text}
          </a>
        </div>
      ))}

      <style jsx>{`
        .anchor_border {
          border-left: 2px solid #1e80ff;
        }
      `}</style>
    </div>
  );
}
