// web/components/Footer.vue
<template>
  <div
    class="footer_shadow flex flex-col justify-evenly items-center p-10 dark:text-dtc dark_bg_gray shadow-xl"
  >
    <div>
      Copyright © {{ year }} - Designed by
      <a
        class="decoration-none text-#000 font-bold hover:underline dark_text_white"
        href="https://github.com/chenmingyong0423/fnote"
        target="_blank"
        >Fnote</a
      >
    </div>
    <div class="flex items-center lt-lg:flex-col">
      <span v-for="(item, index) in records" :key="index" v-html="item"> </span>
    </div>
    <div></div>
  </div>
</template>

<script lang="ts" setup>
import { useConfigStore } from "~/store/config";

const configStore = useConfigStore();

const date = new Date(configStore.website_info.website_runtime * 1000);
const year = date.getFullYear();

const records = configStore.website_info.website_records;
</script>

<style scoped></style>

// nextjs-web/app/components/Footer.tsx
'use client';

import { useConfigContext } from "../context/ConfigContext";

const Footer = () => {
  const { website_info } = useConfigContext();
  
  // 计算年份，基于网站运行时间
  const date = website_info.website_runtime 
    ? new Date(website_info.website_runtime * 1000)
    : new Date();
  const currentYear = date.getFullYear();
  
  // 备案信息，从配置中获取
  const records = website_info.website_records || [];

  return (
    <footer className="flex flex-col justify-evenly items-center p-10 dark:text-gray-300 dark:bg-gray-900 shadow-xl">
      <div>
        Copyright © {currentYear} - Designed by
        <a
          className="no-underline text-black font-bold hover:underline dark:text-white ml-1"
          href="https://github.com/chenmingyong0423/fnote"
          target="_blank"
          rel="noopener noreferrer"
        >
          Fnote
        </a>
      </div>
      <div className="flex items-center lg:flex-row flex-col">
        {records.map((item, index) => (
          <span key={index} dangerouslySetInnerHTML={{ __html: item }} />
        ))}
      </div>
      <div></div>
    </footer>
  );
};

export default Footer;
