// web/components/Notice.vue
<template>
  <div>
    <div
      @click="visible = true"
      class="flex items-center dark:text-dtc dark_bg_gray h-15 bg-#fff mb-5 b-rounded-4 cursor-pointer p-x-5 ease-linear duration-100 md:custom_shadow md:hover:translate-y--2"
    >
      <div class="-i-ph-speaker-high-duotone w-10 h-10 text-orange"></div>
      <div
        ref="marqueeContainer"
        class="ml-5 font-bold overflow-hidden whitespace-nowrap w-full"
        @mouseenter="stopMarquee"
        @mouseleave="startMarquee"
      >
        <span ref="marqueeContent" class="inline-block">
          [{{
            $dayjs(configStore.notice_info.publish_time * 1000).format(
              "YYYY-MM-DD",
            )
          }}] {{ configStore.notice_info.title }}</span
        >
        <span
          ref="marqueeContent2"
          class="inline-block m-l-5"
          v-show="showTheSecondMarquee"
          >{{ configStore.notice_info.title }}</span
        >
      </div>
    </div>
    <!-- 模态框 -->
    <div
      v-if="visible"
      class="fixed z-999 inset-0 bg-black bg-opacity-40 flex items-center justify-center p-4 custom_shadow"
      @click="closeModal"
    >
      <div
        class="bg-white p-6 rounded-4 shadow-lg md:min-w-400px lt-md:max-w-80% dark:text-dtc dark_bg_full_black"
        @click.stop.prevent
      >
        <div class="text-right text-sm text-gray-500 mb-4">
          发布时间:
          {{
            $dayjs(configStore.notice_info.publish_time * 1000).format(
              "YYYY-MM-DD HH:mm:ss",
            )
          }}
        </div>

        <h2 class="text-xl font-bold mb-4">
          {{ configStore.notice_info.title }}
        </h2>
        <p class="indent-8 leading-loose">
          {{ configStore.notice_info.content }}
        </p>
        <Button
          class="w-10% p-2 m-auto m-t-5 text-white bg-#1E80FF"
          name="关闭"
          @click="closeModal"
        ></Button>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ref, onMounted } from "vue";
import { useConfigStore } from "~/store/config";

const configStore = useConfigStore();
const marqueeContainer = ref<HTMLElement | null>(null);
const marqueeContent = ref<HTMLElement | null>(null);
const marqueeContent2 = ref<HTMLElement | null>(null);
const showTheSecondMarquee = ref<boolean>(false);
const visible = ref(false);

const closeModal = () => {
  visible.value = false;
};
const checkMarquee = () => {
  if (marqueeContent.value && marqueeContainer.value) {
    if (marqueeContent.value.offsetWidth > marqueeContainer.value.offsetWidth) {
      marqueeContent.value.classList.add("marquee-animation");
      showTheSecondMarquee.value = true;
      marqueeContent2.value?.classList.add("marquee-animation");
    }
  }
};

const stopMarquee = () => {
  if (marqueeContent.value) {
    marqueeContent.value.style.animationPlayState = "paused";
    if (marqueeContent2.value) {
      marqueeContent2.value.style.animationPlayState = "paused";
    }
  }
};

const startMarquee = () => {
  if (marqueeContent.value) {
    marqueeContent.value.style.animationPlayState = "running";
    if (marqueeContent2.value) {
      marqueeContent2.value.style.animationPlayState = "running";
    }
  }
};

onMounted(checkMarquee);
</script>

<style scoped></style>

// nextjs-web/app/components/Notice.tsx
'use client';

import { useState, useRef, useEffect } from 'react';
import dayjs from 'dayjs';
import { useConfigContext } from '../context/ConfigContext';
import { Button } from 'antd';

export default function Notice() {
  const config = useConfigContext();
  const [visible, setVisible] = useState(false);
  const [showTheSecondMarquee, setShowTheSecondMarquee] = useState(false);
  
  const marqueeContainerRef = useRef<HTMLDivElement>(null);
  const marqueeContentRef = useRef<HTMLSpanElement>(null);
  const marqueeContent2Ref = useRef<HTMLSpanElement>(null);

  const closeModal = () => {
    setVisible(false);
  };

  const checkMarquee = () => {
    if (marqueeContentRef.current && marqueeContainerRef.current) {
      if (marqueeContentRef.current.offsetWidth > marqueeContainerRef.current.offsetWidth) {
        marqueeContentRef.current.classList.add("marquee-animation");
        setShowTheSecondMarquee(true);
        if (marqueeContent2Ref.current) {
          marqueeContent2Ref.current.classList.add("marquee-animation");
        }
      }
    }
  };

  const stopMarquee = () => {
    if (marqueeContentRef.current) {
      marqueeContentRef.current.style.animationPlayState = "paused";
      if (marqueeContent2Ref.current) {
        marqueeContent2Ref.current.style.animationPlayState = "paused";
      }
    }
  };

  const startMarquee = () => {
    if (marqueeContentRef.current) {
      marqueeContentRef.current.style.animationPlayState = "running";
      if (marqueeContent2Ref.current) {
        marqueeContent2Ref.current.style.animationPlayState = "running";
      }
    }
  };

  useEffect(() => {
    checkMarquee();
  }, []);

  // 从ConfigContext中获取notice数据
  const notice = config.notice_info || { 
    show: true, 
    content: '博客升级改版中，感兴趣的小伙伴可以一起参与开发设计！',
    publish_time: Date.now() / 1000 
  };

  // 如果没有通知或通知设置为不显示，则不渲染组件
  if (!notice || !notice.show) {
    return null;
  }

  return (
    <div>
      <div
        onClick={() => setVisible(true)}
        className="flex items-center dark:text-dtc dark:bg-gray-800 h-[60px] bg-white mb-5 rounded-md cursor-pointer px-5 ease-linear duration-100 md:shadow-md md:hover:-translate-y-2"
      >
        <div className="text-orange-500 text-2xl">🔊</div>
        <div
          ref={marqueeContainerRef}
          className="ml-5 font-bold overflow-hidden whitespace-nowrap w-full"
          onMouseEnter={stopMarquee}
          onMouseLeave={startMarquee}
        >
          <span ref={marqueeContentRef} className="inline-block">
            [{dayjs(notice.publish_time * 1000).format("YYYY-MM-DD")}] {notice.title || '通知'}
          </span>
          {showTheSecondMarquee && (
            <span
              ref={marqueeContent2Ref}
              className="inline-block ml-5"
            >
              {notice.title || '通知'}
            </span>
          )}
        </div>
      </div>

      {/* 模态框 */}
      {visible && (
        <div
          className="fixed z-50 inset-0 bg-black bg-opacity-40 flex items-center justify-center p-4 shadow-lg"
          onClick={closeModal}
        >
          <div
            className="bg-white p-6 rounded-md shadow-lg md:min-w-[400px] max-w-[80%] dark:text-dtc dark:bg-gray-900"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="text-right text-sm text-gray-500 mb-4">
              发布时间: {dayjs(notice.publish_time * 1000).format("YYYY-MM-DD HH:mm:ss")}
            </div>

            <h2 className="text-xl font-bold mb-4">
              {notice.title || '通知'}
            </h2>
            <p className="indent-8 leading-loose">
              {notice.content}
            </p>
            <div className="text-center mt-5">
              <Button
                className="w-[10%] p-2 m-auto mt-5 text-white bg-[#1E80FF]"
                onClick={closeModal}
              >
                关闭
              </Button>
            </div>
          </div>
        </div>
      )}

      <style jsx>{`
        @keyframes marquee {
          0% {
            transform: translateX(0);
          }
          100% {
            transform: translateX(-100%);
          }
        }

        .marquee-animation {
          animation: marquee 15s linear infinite;
          animation-play-state: running;
        }
      `}</style>
    </div>
  );
}
