// web/src/components/Footer.tsx
import React from "react";
import FooterRecords from "./FooterRecords";

interface FooterProps {
  websiteRecords: string[];
}

const Footer: React.FC<FooterProps> = ({ websiteRecords }) => (
  <footer className="w-full bg-white dark:bg-[#141414] border-t border-gray-200 dark:border-[#303030] mt-8 mb-4 mx-auto max-w-7xl flex flex-col items-center rounded-xl p-4">
    <div className="flex items-center justify-center w-full text-center text-gray-500 text-sm">
      © {new Date().getFullYear()} Copyright © 2024 - Designed by
      <a
        href="https://github.com/chenmingyong0423/fnote"
        className="ml-1 text-blue-600 hover:underline"
      >
        Fnote
      </a>
    </div>
    <FooterRecords websiteRecords={websiteRecords} />
  </footer>
);

export default Footer;

// web/components/Footer.vue
<template>
  <div
      class="footer_shadow flex flex-col justify-evenly items-center p-10 dark:text-dtc dark_bg_gray shadow-xl">
    <div>
      Copyright © {{ year }} - Designed by
      <a class="decoration-none text-#000 font-bold hover:underline dark_text_white" href="https://github.com/chenmingyong0423/fnote">Fnote</a>
    </div>
    <div class="flex items-center lt-lg:flex-col">
            <span v-for="(item, index) in records" :key="index" v-html="item">
            </span>
    </div>
    <div>
    </div>
  </div>
</template>


<script lang="ts" setup>
import {useHomeStore} from '~/store/home';
const homeStore = useHomeStore()
const date = new Date(homeStore.website_info.live_time * 1000)
const year = date.getFullYear()

const records = homeStore.website_info.records
</script>

<style scoped></style>
